### ISSUE TITLE
Services, performance, and build size

### ISSUE THREAD

**Issue by eyesurewould** [buildabeer/buildabeer#69]
I noticed that performing an `$ng build --prod` results in huge bundles and wondered if that was related to long load times so I took a look at the bundles. If looks like each individual service is pretty large and they all perform roughly the same functions (go get a set of JSON data from an API).

Given that the data is all sourced from the same back end (not multiple APIs), it probably makes sense to build a single service for all the API calling. This would be especially helpful in places where nearly every service is loaded for a component (like recipe runner).

Secondarily, since much of the data retrieved is rarely changed (like the yeast substitutions), it would make sense to either include the JSON file with the source OR use local storage so it only gets retrieved once (or rarely).

**Comment by buildabeer-admin** [comment]
So are you saying instead of having a hops service, malt service, etc. that would do
get /hops, get/malts
we would have 'ingredients service' that would do
get /#{variable}?

I don't think I have any problem with that. Would the http request mapping just map to 'any' then? And does that interfere w/ TS prod build when returning to a controller that 'expects' an IHop or IMalt?

What do you mean by include the JSON file w/ the source?

Storage sounds great as well. Are there strategies we can use to see if data has changed since last retrieved? So that if they load ingredients, realize they need a new one, create it, and go to the recipe designer their new one would actually be there?

**Comment by buildabeer-admin** [comment]
I know how to fix a majority of this issue. Instead of pulling in everything for the recipe screen(s), I need to pull in a list of names and id's. Whenever they add/use one, then do a search for that specific one to add to the list. On the 'advanced' find popups, that is when a full search is required. Once a full search has been done, the simple adds can then use the values from that instead of searching for an individual. I will work on this as soon as recipe runner 2.0 is done. May be a little while still, I'm moving slow as dirt on it due to other commitments, but should have more time to spend on it in a few weeks..

**Comment by eyesurewould** [comment]
No worries - I got busy too. I'll try to get back to open issues next month.

**Comment by jdwyant8** [comment]
I'm alive, I promise!

I put in the most impactful changes, if we still have issues we can reopen.
